version: "3.9"
services:
  influxdb:
    image: "influxdb:2.0.7"
    ports:
      - "8086:8086"
    volumes:
      - $PWD/config.yml:/etc/influxdb2/config.yml
      - $PWD/influx-data:/var/lib/influxdb2
